services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: mustore
      POSTGRES_PASSWORD: mustore
      POSTGRES_DB: mustore
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mustore -d mustore"]
      interval: 3s
      timeout: 5s
      retries: 20
    networks:
      - mustore-network
  redis:
    image: redis:7-alpine
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 3s
      timeout: 3s
      retries: 20
    networks:
        - mustore-network
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - mustore-network
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      CONFIG_PATH: /app/config.yaml
    ports:
      - "8000:8000"
    networks:
      - mustore-network
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_BASE_URL: /api/v1
    depends_on:
      - backend
    ports:
      - "8080:80"
    networks:
      - mustore-network

volumes:
  postgres_data:
  redis_data:

networks:
  mustore-network: