// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/example/": {
            "get": {
                "description": "Retrieve a list of all examples",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "examples"
                ],
                "summary": "Get all examples",
                "responses": {
                    "200": {
                        "description": "Returns a list of examples",
                        "schema": {
                            "$ref": "#/definitions/v1.RawResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/v1.RawResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Create a new example with the provided details",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "examples"
                ],
                "summary": "Create a new example",
                "parameters": [
                    {
                        "description": "Example request",
                        "name": "create_example.Request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/create_example.Request"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Returns the ID of the created example",
                        "schema": {
                            "$ref": "#/definitions/v1.RawResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/v1.RawResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/v1.RawResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/example/{id}": {
            "get": {
                "description": "Retrieve a single example by its ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "examples"
                ],
                "summary": "Get an example by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Example ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Returns the requested example",
                        "schema": {
                            "$ref": "#/definitions/v1.RawResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/v1.RawResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "create_example.Request": {
            "type": "object",
            "properties": {
                "example": {
                    "$ref": "#/definitions/models.Example"
                }
            }
        },
        "models.Example": {
            "type": "object",
            "properties": {
                "first_row": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "second_row": {
                    "type": "integer"
                }
            }
        },
        "v1.RawResponse": {
            "type": "object"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
